import AppLayout from "@/components/layout";
import { ThemeProvider } from "@/components/utils/theme-provider";
import { queryWrapper, websiteQuery } from "@/lib/hygraph-queries";
import { Website } from "@/types/hygraph.type";
import { Ubuntu } from "next/font/google";
import { ReactNode } from "react";
import "../styles/globals.css";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Tonmoy Deb - Frontend Developer",
  description: "Generated by create next app",
};

const getWebsite = async () => {
  const CMS_ENDPOINT = process.env.CMS_ENDPOINT;
  const WEBSITE_ID = process.env.WEBSITE_ID;
  if (!CMS_ENDPOINT || !WEBSITE_ID) return {};

  const response = await fetch(CMS_ENDPOINT, {
    method: "POST",
    body: JSON.stringify({
      query: queryWrapper("getWebsite", [websiteQuery(WEBSITE_ID)]),
    }),
    next: {
      tags: ["website"],
    },
  });

  const { data } = await response.json();

  return data.website;
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const website: Website = await getWebsite();

  return (
    <html lang="en">
      <body className={`${ubuntu.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme={website.defaultTheme?.toLowerCase()}
          enableSystem
        >
          <AppLayout website={website}>{children}</AppLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
