import AppLayout from "@/components/layout";
import { ThemeProvider } from "@/components/utils/theme-provider";
import { Ubuntu } from "next/font/google";
import { ReactNode } from "react";
import "../styles/globals.css";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Tonmoy Deb - Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className}`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AppLayout>{children}</AppLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
